print("fdjnvskjdfnkv")
print("flads is the way we can get itngsd")
print("uday is a good bot ")
print("uday is a bad boy ")
print("fdjnvskjdfnkv")
print("flads is the way we can get itngsd")
print("uday is a good bot ")
print("uday is a bad boy ")
print("fdjnvskjdfnkv")
print("flads is the way we can get itngsd")
print("uday is a good bot ")
print("uday is a bad boy ")
print("hello babai")
print("fdjnvskjdfnkv")
print("line 10 ")
print("flads is the way we can get itngsd")
print("uday is a good bot ")
print("uday is a bad boy ")
